version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  apache:
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.typo3.rule=Host(`typo3.traefik.me`)"
        - "traefik.http.routers.typo3-tls.tls.domains[0].main=typo3.traefik.me"
        - "traefik.http.routers.typo3.tls=true"
        - "traefik.http.services.typo3.loadbalancer.server.port=80"
  phpfpm:
    networks:
      - net
      - serverlampy